export enum Priority {
  BACKLOG = "BACKLOG",
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT",
}

export enum Status {
  BLOCKED = "BLOCKED",
  TODO = "TODO",
  IN_PROGRESS = "IN_PROGRESS",
  UNDER_REVIEW = "UNDER_REVIEW",
  RELEASE_READY = "RELEASE_READY",
  COMPLETED = "COMPLETED",
}
